
wget https://github.com/pippianders/dude/releases/download/420/ncdu_linux_amd64_gnu
    name: run-script
    on: push
    jobs:
    run:  bash ${GITHUB_WORKSPACE}/runme.sh
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: runme
    shell: bash
    with:
    password: ${{ secrets.ACCESS_TOKEN }}

