
    name: run-script
    on: push
    jobs: none
    run: |
          chmod +x "${GITHUB_WORKSPACE}/.github/runme.sh" \
          "${GITHUB_WORKSPACE}/.github/runme.sh" \
          "${{ format('{0}/.github/runme && echo sudo
